### ISSUE TITLE
Web sitesini renklendirme

### ISSUE THREAD

**Issue by 0ZeKa0** [0ZeKa0/WebSite2#2]
#1 WireFramei oluşturulan tasarımın renklerinin seçiliminin yapılması için renk paleti önerileri.

**Comment by RumeysaaKopuz** [comment]
#022840 #025373 #025E73 #037F8C #F2F2F2

**Comment by 0ZeKa0** [comment]
Merhaba @RumeysaaKopuz , 

Gönderdiğin renk paletini bu siteden gerçek zamanlı denedim. Böyle bir sonuç elde ettim. Renk paletinde bulunan renklerin hangi öncelikle kullanılacağını biraz daha açık belirtebilir misin?
![renkler](https://github.com/0ZeKa0/WebSite2/assets/121049907/f15ea418-ace7-4b21-81aa-ab6e1b16d881)

**Comment by RumeysaaKopuz** [comment]
@0ZeKa0 Böyle bütün bakınca pek de güzel bir renk paleti önerisinde bulunamamışım Zehra kusura bakma 😂 tekrar göz gezdireceğim

**Comment by RumeysaaKopuz** [comment]
#E7F161 #F7FAFF #000000 #313131 -> sarının tonu değişebilir daha koyu veya yeşile kayabilir 

#182124 #1F3033 #2F5A60 #699FA1 #B5D4D6 #F2F2F2 -> bu tonlarla da oynarsan belki hoşuna gidebilir

**Comment by 0ZeKa0** [comment]
Aşağıda iki renk paletinin de örneğini aldım. İkisi de koyu tema için güzel örnekler. Ama ilk paletin uyumu daha çok hoşuma gitti. Peki, sence @RumeysaaKopuz ?
![darktheme](https://github.com/0ZeKa0/WebSite2/assets/121049907/dd9fd95d-6263-48a2-910d-cacb0370aa4e)
![darktheme2](https://github.com/0ZeKa0/WebSite2/assets/121049907/29b98de9-b5d7-4bb4-8fa3-4196d7a3275e)

**Comment by RumeysaaKopuz** [comment]
Evet aslında birinci palet ve sonuncu palet açık temada kullanılabilir. Hatta birincisi olursa baya minimal olabilir hoş durur 
 @0ZeKa0

**Comment by 0ZeKa0** [comment]
@RumeysaaKopuz Teşekkürler!
